name: Bug report 🐛
description: Something not working as expected? This is the place to report your issue.
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: |
        # Hi there! :wave:

        Thanks for taking the time to fill out this bug report. Please use issues only to report bugs.
        **If you want to discuss about something that doesn't match your taste, give feedback or chat about a topic, visit [Discussions](https://github.com/Vira-Theme/vira-theme-support/discussions).
        Every issue opened that's not related to a bug or icon request will be closed instantly.**
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into. If possible attach a screenshot or video."
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: 'How do we reproduce the error you described above? Does an additional extension need to be installed? For issues with syntax highlighting, consider adding some example code and the language being used.'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Type '....'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: 'What version of `vsc-vira-theme` are you using?'
      placeholder: v34.5.0
    validations:
      required: true
  - type: input
    id: vsc-version
    attributes:
      label: VSCode Version
      description: 'What version of Visual Studio Code are you using?'
      placeholder: v1.92.0
    validations:
      required: true
  - type: dropdown
    id: theme
    attributes:
      label: Theme
      description: In which themes(s) are you experiencing the issue?
      multiple: false
      options:
        - Both of them
        - Vira Theme
        - Vira Theme Hight Contrast
        - Vira Theme Darker
        - Vira Theme Darker High Contrast
        - Vira Theme Ocean
        - Vira Theme Ocean High Contrast
        - Vira Theme Palenight
        - Vira Theme Palenight High Contrast
        - Vira Theme Deepforest
        - Vira Theme Deepforest High Contrast
        - Vira Theme Lighter
        - Vira Theme Lighter High Contrast
